services:
  back-end:
    build:
      context: ./be-pages
      dockerfile: ./Dockerfile
      target: development
    command: npm run start:dev
    env_file:
      - ./be-pages/.env
    depends_on:
      - db
    volumes:
      # - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '9001:9001'
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local

      