apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-contact-form-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: be-contact-form
  template:
    metadata:
      labels:
        app: be-contact-form
    spec:
      containers:
        - name: be-contact-form
          # image: us.gcr.io/ticketing-dev-359710/be-auth
          image: manelcastro/be-contact-form
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: MONGO_URI
              value: "mongodb://be-contact-form-mongo-srv:27017/be-contact-form" # Not issue to push to Git since only useful inside cluster
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: be-contact-form-srv
spec:
  selector:
    app: be-contact-form
  type: ClusterIP
  ports:
    - name: be-contact-form
      protocol: TCP
      port: 9000
      targetPort: 9000
