import type { Metadata } from "next";
import { Inter, Montserrat, Open_Sans } from "next/font/google";
import StyledComponentsRegistry from "@/providers/styled-components-registry";
import "@/app/globals.css";
import Navbar from "@/sections/navbar";
import { useLocale } from "next-intl";
import { notFound } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });
const openSans = Open_Sans({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-open-sans",
});
const montserrat = Montserrat({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const locale = useLocale();

  // Show a 404 error if the user requests an unknown locale
  if (params.locale !== locale) {
    notFound();
  }
  return (
    <html>
      <body
        className={`${inter.className} ${openSans.variable} ${montserrat.variable}`}
      >
        <StyledComponentsRegistry>
          <nav>
            <Navbar locale={locale} />
          </nav>
          {children}
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
