import type { Metadata } from "next";
import { Inter, Montserrat, Open_Sans } from "next/font/google";
import StyledComponentsRegistry from "../providers/styled-components-registry";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const openSans = Open_Sans({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-open-sans",
});
const montserrat = Montserrat({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${openSans.variable} ${montserrat.variable}`}
      >
        <StyledComponentsRegistry>
          <nav>This will be a navbar</nav>
          {children}
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
